---

- name: Create Validation Records
  community.dns.hetzner_dns_record:
    type: TXT
    value: "{{ le_challenge.challenge_data[item.fqdn]['dns-01'].resource_value }}"
    state: present
    ttl: 60
    record: "{{ le_challenge.challenge_data[item.fqdn]['dns-01'].record }}"
    zone_name: "{{ item.dns_zone }}"
  delegate_to: localhost

- name: Wait 60s for DNS to propagate
  ansible.builtin.wait_for:
    timeout: 60
  delegate_to: localhost
